name:                cs517prj
version:             0.1.0.0
github:              "githubuser/cs517prj"
license:             BSD3
author:              Parisa Ataei
maintainer:          ataeip@oregonstate.edu
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/cs517prj#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6 && <1
- mtl
- sbv
- HDBC
- convertible
- bytestring
- time 

library:
  source-dirs: src

default-extensions:
    - GeneralizedNewtypeDeriving
    - DeriveDataTypeable
    - StandaloneDeriving
    - FlexibleInstances

executables:
  cs517prj-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cs517prj

tests:
  cs517prj-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cs517prj
